<?php

$produtos = array(
    0 => array('nome'=>'CAM THOMAS', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'cam.avif'),
    1 => array('nome'=>'RAYJON TUCKER', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'tucker.avif'),
    2 => array('nome'=>'ISH WAINRIGHT', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'ish.avif'),
    3 => array('nome'=>'NAZ REID', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'naz.avif'),
    4 => array('nome'=>'TONY BRADLEY', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'tony.avif'),
    5 => array('nome'=>'JARETT CULVER', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'culver.avif'),
    6 => array('nome'=>'JOHN KONCHAR', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'john.avif'),
    7 => array('nome'=>'SVI MY KHAILIUK', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'svi.avif'),
    8 => array('nome'=>'STERLING BROWN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'brown.avif'),
    9 => array('nome'=>'STEVEN ADAMS', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'adams.avif'),
    10 => array('nome'=>'LEANDRO BOLMARO', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'bolmaro.avif'),
    11 => array('nome'=>'NAJI MARSHALL', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'naji.avif'),
    12 => array('nome'=>'MARKIEFF MORRIS', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'markieff.avif'),
    13 => array('nome'=>'JAVALE MCGEE', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'mcgee.avif'),
    14 => array('nome'=>'TAUREAN PRINCE', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'prince.avif'),
    15 => array('nome'=>'ISAAC BONGA', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'bonga.avif'),
    16 => array('nome'=>'DAYRON SHARPE', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'sharpe.avif'),
    17 => array('nome'=>'XAVIER TILLMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'tillman.avif'),
    18 => array('nome'=>'GARETT TEMPLE', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'temple.avif'),
    19 => array('nome'=>'TONY SNELL', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'snell.avif'),
    20 => array('nome'=>'STEVEN ADAMS', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'adams.avif'),
    21 => array('nome'=>'MAXI KLEBER', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'maxi.avif'),
    22 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    23 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    24 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    25 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    26 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    27 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    28 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    29 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    30 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    31 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    32 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    33 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    34 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    35 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    36 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    37 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    38 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    39 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    40 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    41 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    42 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    43 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    44 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    45 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    46 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    47 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    48 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    49 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    
)
?>