<?php

$produtos = array(
    0 => array('nome'=>'CAM THOMAS', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'cam.avif'),
    1 => array('nome'=>'RAYJON TUCKER', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'tucker.avif'),
    2 => array('nome'=>'ISH WAINRIGHT', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'ish.avif'),
    3 => array('nome'=>'NAZ REID', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'naz.avif'),
    4 => array('nome'=>'TONY BRADLEY', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'tony.avif'),
    5 => array('nome'=>'JARETT CULVER', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'culver.avif'),
    6 => array('nome'=>'JOHN KONCHAR', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'john.avif'),
    7 => array('nome'=>'SVI MY KHAILIUK', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'svi.avif'),
    8 => array('nome'=>'STERLING BROWN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'brown.avif'),
    9 => array('nome'=>'STEVEN ADAMS', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'adams.avif'),
    10 => array('nome'=>'LEANDRO BOLMARO', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'bolmaro.avif'),
    11 => array('nome'=>'NAJI MARSHALL', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'naji.avif'),
    12 => array('nome'=>'MARKIEFF MORRIS', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'markieff.avif'),
    13 => array('nome'=>'JAVALE MCGEE', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'mcgee.avif'),
    14 => array('nome'=>'TAUREAN PRINCE', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'prince.avif'),
    15 => array('nome'=>'ISAAC BONGA', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'bonga.avif'),
    16 => array('nome'=>'DAYRON SHARPE', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'sharpe.avif'),
    17 => array('nome'=>'XAVIER TILLMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'tillman.avif'),
    18 => array('nome'=>'GARETT TEMPLE', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'temple.avif'),
    19 => array('nome'=>'TONY SNELL', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'snell.avif'),
    20 => array('nome'=>'STEVEN ADAMS', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'adams.avif'),
    21 => array('nome'=>'MAXI KLEBER', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'maxi.avif'),
    22 => array('nome'=>'JAKE LAYMAN', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'layman.avif'),
    23 => array('nome'=>'MACACO #24', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco24.png'),
    24 => array('nome'=>'MACACO #25', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco25.png'),
    25 => array('nome'=>'MACACO #26', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco26.png'),
    26 => array('nome'=>'MACACO #27', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco27.png'),
    27 => array('nome'=>'MACACO #28', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco28.png'),
    28 => array('nome'=>'MACACO #29', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco29.png'),
    29 => array('nome'=>'MACACO #30', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco30.png'),
    30 => array('nome'=>'MACACO #31', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco31.png'),
    31 => array('nome'=>'MACACO #32', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco32.png'),
    32 => array('nome'=>'MACACO #33', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco33.png'),
    33 => array('nome'=>'MACACO #34', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco34.png'),
    34 => array('nome'=>'MACACO #35', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco35.png'),
    35 => array('nome'=>'MACACO #36', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco36.png'),
    36 => array('nome'=>'MACACO #37', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco37.png'),
    37 => array('nome'=>'MACACO #38', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco38.png'),
    38 => array('nome'=>'MACACO #39', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco39.png'),
    39 => array('nome'=>'MACACO #40', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco40.png'),
    40 => array('nome'=>'MACACO #41', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco41.png'),
    41 => array('nome'=>'MACACO #42', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco42.png'),
    42 => array('nome'=>'MACACO #43', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco43.png'),
    43 => array('nome'=>'MACACO #44', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco44.png'),
    44 => array('nome'=>'MACACO #45', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco45.png'),
    45 => array('nome'=>'MACACO #46', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco46.png'),
    46 => array('nome'=>'MACACO #47', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco47.png'),
    47 => array('nome'=>'MACACO #48', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco48.png'),
    48 => array('nome'=>'MACACO #49', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'macaco49.png'),
    49 => array('nome'=>'MACACO #50', 'preco'=>'R$ 1.000,00', 'descricao'=>'NBA', 'imagem'=>'.avif'),
)
?>